config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
   root to: "home#index"
   resources :projects do
    member do
      get 'add_user', to: 'project_users#add_user'
      get 'edit_user', to: 'project_users#edit_user'
      patch 'update_user', to: 'project_users#update_user'
      delete 'remove_user', to: 'project_users#remove_user'
      post 'assign_role',to: 'project_users#assign_role'
    end
    #this route is collection route does not require id for assign role 
    # resources :project_users, only: [:create] do
    #   post 'assign_role', on: :collection
    # end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users

  enum status: { not_started: 0, in_progress: 1, completed: 2 }

  validates :status, inclusion: { in: %w[not_started in_progress completed] }


  validates :title, :description, :start_date, :end_date, presence: true
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
  
  validates :role, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :project_users, dependent: :destroy
         has_many :projects
         has_many :assigned_projects, through: :project_users, source: :project

         
  before_create :set_default_role

  def set_default_role
    self.role ||= 'regular_user' # Set default role to 'regular_user' if not chosen
  end
 

  def project_manager?
    role == 'project_manager'
  end

  def regular_user?
    role == 'regular_user'
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index
    render
  end
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  before_action :authorize_project_manager, only: [:add_user, :assign_role, :remove_user,:update_user]

  def add_user
    #  debugger
    @project = Project.find(params[:id])
    @users = User.where.not(id: @project.users.pluck(:id))
    @users = @users.where.not(id: current_user.id)
  end

  def assign_role
        # debugger
      @project = Project.find(params[:id])
      @project_user = @project.project_users.new(project_user_params)
      if @project_user.save!
        redirect_to @project, notice: 'User was successfully added to the project with the role.'
      else
        render :add_user, alert: 'Failed to add user to the project.'
      end
    end

  def remove_user
    @project = Project.find(params[:id])
    project_user = @project.project_users.find_by(user_id: params[:user_id])
    
    if project_user&.destroy
      redirect_to @project, notice: 'User was successfully removed from the project.'
    else
      redirect_to @project, alert: 'Failed to remove user from the project.'
    end
  end

  def edit_user
    @project = Project.find(params[:id])
    @project_user = @project.project_users.find_by(user_id: params[:user_id])
  end
  
  def update_user
    @project = Project.find(params[:id])
    @project_user = @project.project_users.find_by(user_id: params[:user_id])
  
    if @project_user.update(project_user_params)
      redirect_to @project, notice: 'User role was successfully updated.'
    else
      redirect_to @project, alert: 'Failed to update user role.'
    end
  end

  private

  def project_user_params
    params.permit(:user_id, :role)
  end

  def authorize_project_manager
    redirect_to(root_path, alert: "You are not authorized to perform this action.") unless current_user.role == "project_manager"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_project_manager, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index 
    @projects = current_user.projects
  end

  def show
  end

  def new 
    @project = current_user.projects.build
    if @project.nil?
      redirect_to root_path, notice: "Project could not be created."
    end
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to projects_path, notice: "Project has been created successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'Project was successfully deleted.'
    else
      redirect_to projects_path, alert: 'Failed to delete the project.'
    end
  end
 
  private 
  
  def set_project
    @project = current_user.projects.find_by(id: params[:id])
    redirect_to projects_path, alert: "Project not found or you don't have access." if @project.nil?
  end

  def project_params
    params.require(:project).permit(:title, :description, :start_date, :end_date, :status)
  end

  def authorize_project_manager
    redirect_to(root_path, alert: "You are not authorized to perform this action.") unless current_user.role == "project_manager"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<h1>HOME PAGE</h1>
  <ul class="navbar-nav">
  <% if user_signed_in? %> Logged in as <strong> <%= current_user.email%></strong>
    <% if current_user.role == "project_manager" %>
        <li class="nav-item">
          <%= link_to "Manage Projects", projects_path, class: 'navbar-link' %>
        </li>
        <li class="nav-item">
          <%#= link_to "Team Management", teams_path, class: 'navbar-link' %>
        </li>
      <% elsif current_user.role == "regular_user" %>
        <li class="nav-item">
          <%#= link_to "View Assigned Projects", assigned_projects_path, class: 'navbar-link' %>
        </li>
      <% end %>
  <li class="nav-item">
  <%= link_to "Edit Profile", edit_user_registration_path, :class => 'navbar-link' %>
  </li>
  <li class="nav-item">
  <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete },:class => 'navbar-link' %>
  </li>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

<% else %>
<li class="nav-item">
<%= link_to 'Sign In', new_user_session_path,:class => 'navbar-link' %>
</li>
<li class="nav-item">
<%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link' %>
</li>
<% end %>
</ul>



  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

      <%#= stylesheet_link_tag 'application', media: 'all' %>
      <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice if notice.present? %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>

   
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/project_users/add_user.html.erb
<h2>Add User to Project</h2>
<%= form_with url: assign_role_project_path(@project), local: true do |form| %>
  <div class="form-group">
    <%= form.label :user_id, "Select User" %>
    <%= form.collection_select :user_id, @users, :id, :email, prompt: "Choose a user", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :role, "Assign Role" %>
    <%= form.select :role, [['Team Lead', 'team_lead'], ['Developer', 'developer']], prompt: "Select role", class: "form-control" %>
  </div>

  <%= form.submit "Add User to Project", class: "btn btn-primary" %>
<% end %>

app/views/project_users/edit_user.html.erb
<h2>Edit Role for <%= @project_user.user.email %></h2>

<%= form_with url: update_user_project_path(@project, user_id: @project_user.user.id), method: :patch, local: true do |f| %>
  <div class="form-group">
    <%= f.label :role, "Select New Role" %>
    <%= f.select :role, options_for_select(["Team Lead", "Developer"], @project_user.role), class: 'form-control' %>
  </div>

  <%= f.submit "Update Role", class: "btn btn-primary" %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |form|%>
  <div class= "row">
    <div class = "col-lg-4"> 
        <div class="from-group">
          <%=form.label :title, class:'mb-2'%>
          <%= form.text_field :title, class:"form-control form-control-lg rounded-0"%>
        </div>
        <% @project.errors.full_messages_for(:title).each do |msg|%>
            <p class = "text-danger"><%= msg%> </p>
        <% end%>
    </div>
    <div class="col-lg-4">
      <div class = "form-group">
        <%= form.label :description, class:"mb-2"%>
        <%= form.text_field :description, class:"form-control form-control-lg rounded-0"%> 
      </div>
    </div>
  </div>
        

  <div class="row">
    <div class= "col-lg-4 mt-4">
      <div class="form-group">
      <%= form.label :start_date , class:"mb-2"%>
      <%= form.date_field :start_date, class:"form-control form-control-lg rounded-0"%>
      </div>
      
      <% @project.errors.full_messages_for(:start_date).each do |msg|%>
      <p class="text-danger"> <%= msg %> </p> 
      <%end%>
    </div>

    <div class= "col-lg-4 mt-4">
      <div class="form-group">
        <%= form.label :end_date , class:"mb-2"%>
        <%= form.date_field :end_date, class:"form-control form-control-lg rounded-0"%>
      </div>
      
        <% @project.errors.full_messages_for(:end_date).each do |msg|%>
        <p class="text-danger"> <%= msg %> </p> 
        <%end%>
    </div>
  </div>
  <div class="col-lg-4 mt-4">
  <div class="form-group">
    <%= form.label :status, class: "mb-2" %>
    <%= form.select :status, options_for_select([['Not_Started', 'not_started'],['In Progress', 'in_progress'], ['Completed', 'completed']]) , class: "form-control form-control-lg rounded-0" %>
  </div>
  <br>

  <% @project.errors.full_messages_for(:status).each do |msg| %>
    <p class="text-danger"> <%= msg %> </p>
  <% end %>
</div>

<div class="row">
   <div class= "col-lg-4 mt-2">
     <%= form.submit class: "btn btn-primary btn-lg mb-4 rounded-0"%>
     <%= link_to "Back To Projects" , projects_path,class: "btn btn-outline-primary btn-lg mb-4 rounded-0" %>
   </div>
</div>

<%end%>

app/views/projects/edit.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-4 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Edit Project Information </h2>
        </div>
    </div>
    <%= render 'form', post: @project %>
</div>

app/views/projects/index.html.erb
<div class="col-lg-12">
  <%#= flash[:notice] %>
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Listing Projects</h2>
    </div>
  </div>
  
  <%= link_to "Create New Project", new_project_path, class: "btn btn-primary btn-lg mb-4" %>
  <%= link_to 'Back To Home Page', root_path, class: 'btn btn-primary btn-lg mb-4' %>

  <% if @projects.any? %>

  <table class="table table-bordered text-center">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td><%= project.start_date %></td>
          <td><%= project.end_date %></td>
          <td><%= project.status %></td>
          <td>
            <%= link_to 'Show', project_path(project), class: 'btn btn-info' %>
            <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning' %>
            <%= link_to 'Delete', project_path(project),  data: { "turbo-method": :delete,turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <%end%>
</div>

app/views/projects/new.html.erb
<!-- app/views/posts/new.html.erb -->
<h1>Create New project</h1>

<%= render 'form', post: @project %>

<%= link_to 'Back To Home Page', root_path, class: 'btn btn-secondary' %>

app/views/projects/show.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-4 mb-5">
    <div class="card-body">
      <h2 class="text-center">Project Details</h2>
      
      <!-- Project Information -->
      <div class="row mt-5">
        <div class="col-lg-6">
          <h3 class="mb-3">Project Information</h3>
          <p class="lead"><strong>Title: </strong><%= @project.title %></p>
          <p class="lead"><strong>Description: </strong><%= @project.description %></p>
          <p class="lead"><strong>Status: </strong><%= @project.status %></p>
          <p class="lead"><strong>Start Date: </strong><%= @project.start_date.strftime("%B %d, %Y") %></p>
          <p class="lead"><strong>End Date: </strong><%= @project.end_date.present? ? @project.end_date.strftime("%B %d, %Y") : "Ongoing" %></p>
        </div>

        <!-- Additional Information -->
        <div class="col-lg-6">
          <h3 class="mb-3">Additional Information</h3>
          <p class="lead"><strong>Created By: </strong><%= @project.user.email%></p>
          <p class="lead"><strong>Last Updated: </strong><%= @project.updated_at.strftime("%B %d, %Y %I:%M %p") %></p>
          <p class="lead"><strong>Current Phase: </strong><%= @project.status.capitalize %></p>
        </div>
      </div>

      <div class="col-lg-6">
        <h3>Project Team</h3>
        <%= link_to 'Add User', add_user_project_path(@project), class: 'btn btn-primary' %>
        <table class="table">
          <thead>
            <tr>
              <th>User</th>
              <th>Role</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @project.project_users.each do |project_user| %>
              <tr>
                <td><%= project_user.user.email %></td>
                <td><%= project_user.role %></td>
                <td>
                  <%= link_to 'Remove', remove_user_project_path(@project, user_id: project_user.user.id), data: { "turbo-method": :delete,turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                  <%= link_to 'Edit Role', edit_user_project_path(@project, user_id: project_user.user.id), class: 'btn btn-primary' %>

                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <!-- Action Buttons -->
      <%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-primary btn-lg" %>
      <%= link_to "Back to Projects", projects_path, class: "btn btn-outline-primary btn-lg" %>
    </div>
  </div>
</div>